// orgConfig.js
//
// Looks up one tenant's row in the shared, multi-tenant Catalyst project's
// `OrgConfig` Data Store table.
//
// CORRECTED, MINIMAL SCOPE (see plan's "Correction" section, confirmed by
// Zoho Marketplace support): this table does NOT hold Engati/WorkDrive
// credentials anymore - those are CRM Variables now (Zoho's confirmed
// guidance for per-org third-party API keys), read by the widget and passed
// straight through per-request to liveChatSender/fileUpload/whatsappProxy.
// This table's remaining job is tenant identity/lifecycle: resolving a Zoho
// CRM org id to its webhook_slug (the opaque token embedded in that org's
// Engati webhook URL, see liveChatWebhook's findByWebhookSlug below),
// whether the org is still an active install, and ONE piece of genuinely
// sensitive per-org config that couldn't move to a CRM Variable the same
// way: crm_function_url - the org's bundled Deluge Lead-sync function's own
// REST API URL (URL + zapikey together, see deluge/leadSync.dg), which
// liveChatWebhook calls directly. Kept in OrgConfig rather than a CRM
// Variable because it's a bearer-credential-bearing URL, entered once via
// the Settings page (functions/orgConfigApi), write-only the same way
// secrets were treated before the wider CRM-Variables correction - GET
// never echoes it back, only an isSet flag.
//
// NOTE: this file is intentionally duplicated across functions/liveChatWebhook
// and functions/orgConfigApi (previously also fileUpload/whatsappProxy, which
// no longer need it at all post-correction) - Catalyst deploys each function
// folder independently, functions cannot require() a sibling function's
// files. Keep both copies in sync; SETUP.md already flags an analogous
// divergence risk between functions/ and catalyst-functions/, this is the
// same category of trap.
//
// Table schema (create in both Development and Production, same as
// LiveChatEvents - see SETUP.md Phase 3):
//   OrgConfig
//     org_id                  Text, should be unique per row
//     webhook_slug             Text, should be unique per row
//     crm_function_url        Text, write-only from the caller's POV - see above
//     status                   Text ("active" | "inactive" - see extensionLifecycle)
//     installed_at, updated_at Text (ISO timestamps)

// ZCQL has no parameter binding - every value interpolated into a query
// below MUST go through one of these whitelists first.
function safeDigits(v) {
  return String(v || '').replace(/[^0-9]/g, '');
}
function safeSlug(v) {
  // webhook_slug is generated by extensionLifecycle as base64url, so this
  // whitelist matches that alphabet - anything else could only be a bogus/
  // malicious query param, never a real slug.
  return String(v || '').replace(/[^A-Za-z0-9_-]/g, '');
}

function rowOrNull(rows) {
  var row = rows && rows[0] && rows[0].OrgConfig;
  return row || null;
}

// Used by liveChatSender/fileUpload/whatsappProxy - the widget always knows
// its own org id (see app.js CURRENT_ORG_ID) and sends it on every request.
function findByOrgId(catalystApp, orgId) {
  var safe = safeDigits(orgId);
  if (!safe) { return Promise.resolve(null); }
  return catalystApp.zcql().executeZCQLQuery(
    "SELECT * FROM OrgConfig WHERE org_id = '" + safe + "' AND status = 'active' LIMIT 1"
  ).then(rowOrNull);
}

// Used only by liveChatWebhook - Engati's payload carries no org id at all
// (see index.js header comment), so tenant resolution instead goes through
// the opaque webhook_slug embedded in the query string of the "External
// Webhook URL" each org pastes into Engati's Configure screen. Query string
// only, never a path segment - see the platform-quirk comment in
// functions/fileUpload/index.js's shortIdFromUrl, the same constraint
// applies here.
function findByWebhookSlug(catalystApp, slug) {
  var safe = safeSlug(slug);
  if (!safe) { return Promise.resolve(null); }
  return catalystApp.zcql().executeZCQLQuery(
    "SELECT * FROM OrgConfig WHERE webhook_slug = '" + safe + "' AND status = 'active' LIMIT 1"
  ).then(rowOrNull);
}

function slugFromUrl(url) {
  var qIdx = String(url || '').indexOf('?');
  if (qIdx === -1) return null;
  var params = new URLSearchParams(url.slice(qIdx));
  return params.get('t') || null;
}

module.exports = { findByOrgId: findByOrgId, findByWebhookSlug: findByWebhookSlug, slugFromUrl: slugFromUrl };
