// orgConfigApi
//
// Backend for the Settings page (settings.html/settings.js, plan Phase B).
//
// CORRECTED SCOPE (see plan's "Correction" section, confirmed by Zoho
// Marketplace support): Engati and WorkDrive credentials do NOT live here -
// Zoho's guidance is CRM Variables for per-org third-party credentials (see
// app.js/SETUP.md), read directly by the widget, no custom API needed.
// This function's remaining job:
//   GET  - tell an org's admin their own webhook_slug-based Engati webhook
//          URL (generated by functions/extensionLifecycle at install time -
//          can't be a self-set CRM Variable since the admin doesn't choose
//          it) and whether a Lead-sync function URL is already saved.
//   POST - accept ONE field, crm_function_url: the org's bundled Deluge
//          Lead-sync function's own REST API URL (see deluge/leadSync.dg).
//          Write-only, same "blank means unchanged" convention the removed
//          credential fields used to follow - GET never echoes this back,
//          only an isSet flag, since the URL carries a bearer credential
//          (the zapikey) in its query string.
//
// *** SECURITY GAP, same as before the wider correction: no verification
// yet that the caller is actually an admin of the claimed orgId - see
// verifyCallerOrgId() below, an unimplemented stub. Lower stakes than when
// this function handled Engati/WorkDrive secrets directly, but writing
// crm_function_url is still a real capability (redirect another org's Lead
// sync to an attacker-controlled endpoint) - fix before any public-facing
// deployment. ***

const catalyst = require('zcatalyst-sdk-node');
const { findByOrgId } = require('./orgConfig');

function readBody(req) {
  return new Promise(function (resolve) {
    var data = '';
    req.on('data', function (chunk) { data += chunk; });
    req.on('end', function () { resolve(data); });
    req.on('error', function () { resolve(''); });
  });
}

function safeDigits(v) { return String(v || '').replace(/[^0-9]/g, ''); }

// *** STUB - see file header. Always "passes" today. ***
function verifyCallerOrgId(req, orgId) {
  console.error('[orgConfigApi] SECURITY: verifyCallerOrgId() is an unimplemented stub - caller-claimed orgId=' + orgId + ' is NOT being verified. Do not run this in a public-facing deployment until this is fixed - see file header.');
  return true;
}

function webhookUrlFor(req, slug) {
  var host = (req.headers && (req.headers.host || req.headers[':authority'])) || '';
  host = host.replace(/:443$/, '');
  return 'https://' + host + '/server/liveChatWebhook/?t=' + slug;
}

function handleGet(req, res, headers, orgId) {
  var catalystApp = catalyst.initialize(req);
  findByOrgId(catalystApp, orgId).then(function (row) {
    if (!row) {
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 404, body: JSON.stringify({ error: 'no active OrgConfig row for this org - has the extension finished installing?' }) }));
      return;
    }
    res.writeHead(200, headers);
    res.end(JSON.stringify({
      statusCode: 200,
      body: JSON.stringify({
        webhookUrl: row.webhook_slug ? webhookUrlFor(req, row.webhook_slug) : null,
        crmFunctionUrl_isSet: !!row.crm_function_url
      })
    }));
  }).catch(function (e) {
    console.error('[orgConfigApi] GET failed: ' + (e && e.message));
    res.writeHead(200, headers);
    res.end(JSON.stringify({ statusCode: 502, body: JSON.stringify({ error: (e && e.message) || String(e) }) }));
  });
}

function handlePost(req, res, headers, orgId, input) {
  var catalystApp = catalyst.initialize(req);
  findByOrgId(catalystApp, orgId).then(function (row) {
    if (!row) {
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 404, body: JSON.stringify({ error: 'no active OrgConfig row for this org - has the extension finished installing?' }) }));
      return;
    }
    if (typeof input.crmFunctionUrl !== 'string' || !input.crmFunctionUrl) {
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 400, body: JSON.stringify({ error: 'crmFunctionUrl required' }) }));
      return;
    }
    catalystApp.datastore().table('OrgConfig').updateRow({
      ROWID: row.ROWID,
      crm_function_url: input.crmFunctionUrl,
      updated_at: new Date().toISOString()
    }).then(function () {
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 200, body: JSON.stringify({ ok: true }) }));
    }).catch(function (e) {
      console.error('[orgConfigApi] update failed: ' + (e && e.message));
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 502, body: JSON.stringify({ error: (e && e.message) || String(e) }) }));
    });
  }).catch(function (e) {
    console.error('[orgConfigApi] POST lookup failed: ' + (e && e.message));
    res.writeHead(200, headers);
    res.end(JSON.stringify({ statusCode: 502, body: JSON.stringify({ error: (e && e.message) || String(e) }) }));
  });
}

module.exports = function (req, res) {
  var headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json'
  };

  if (req.method === 'OPTIONS') {
    res.writeHead(204, headers);
    res.end();
    return;
  }

  readBody(req).then(function (raw) {
    var input;
    try { input = JSON.parse(raw || '{}'); } catch (e) { input = {}; }

    // GET carries orgId as a query param (no body) - same req.url-query-
    // string-only platform quirk documented in fileUpload's shortIdFromUrl.
    // POST carries it in the JSON body like every other function here.
    var orgIdFromQuery = null;
    var qIdx = String(req.url || '').indexOf('?');
    if (qIdx !== -1) {
      orgIdFromQuery = new URLSearchParams(req.url.slice(qIdx)).get('orgId');
    }
    var orgId = safeDigits(orgIdFromQuery || input.orgId);

    if (!orgId) {
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 400, body: JSON.stringify({ error: 'orgId required' }) }));
      return;
    }
    if (!verifyCallerOrgId(req, orgId)) {
      // Unreachable today (stub always returns true) - structured so the
      // real check just has to start returning false to take effect.
      res.writeHead(200, headers);
      res.end(JSON.stringify({ statusCode: 403, body: JSON.stringify({ error: 'unauthorized' }) }));
      return;
    }

    if (req.method === 'GET') {
      handleGet(req, res, headers, orgId);
    } else {
      handlePost(req, res, headers, orgId, input);
    }
  });
};
